"""Fixed design constants from the thesis project structure."""

N_VALUES = [500, 1000]
P_VALUES = [200, 500]
FULL_CONTROL_BENCHMARK_DGPS = ["dgp1"]
FULL_CONTROL_BENCHMARK_N_VALUES = [500, 1000]
FULL_CONTROL_BENCHMARK_P_VALUES = [20, 50, 100]
FULL_CONTROL_BENCHMARK_PI_VALUES = [1.0]
FULL_CONTROL_BENCHMARK_TAUS = [0.25, 0.5, 0.75]
FULL_CONTROL_BENCHMARK_OUTPUT = "results/raw/full_control_ivqr_results.csv"
FULL_CONTROL_BENCHMARK_ALPHA_GRID_SIZE = 9
PI_VALUES = [1.0, 0.5, 0.25, 0.10]
TAUS = [0.25, 0.50, 0.75]
DGPS = ["dgp1", "dgp2", "dgp3"]

R_FAST = 10
R_MAIN = 500
R_FULL_CONTROL_BENCHMARK = 500
FAST_OUTPUT = "results/raw/fast_mode_results.csv"
FULL_OUTPUT = "results/raw/full_mode_results.csv"
DEFAULT_OUTPUT = FULL_OUTPUT
DEFAULT_ALPHA_GRID_SIZE = 9
DEFAULT_DML_K_FOLDS = 3
DEFAULT_N_JOBS = 6
DEFAULT_BATCH_SIZE = 10
DEFAULT_CHUNK_COUNT = 1
DEFAULT_QUANTREG_MAX_ITER = 1000
K_FOLDS = DEFAULT_DML_K_FOLDS

RHO_X = 0.5
RHO_UV = 0.5
DF_T = 5
